[project]
name = "pytheory"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pytuning",
    "numeral",
    "pygame",
    "scipy",
]
